services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION}
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      # Enable or disable basic authentication (true/false)
      - N8N_BASIC_AUTH_ACTIVE=false
      # Enforce strict permissions on settings file (recommended for security)
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # Enable n8n runners for distributed workflows (true/false)
      - N8N_RUNNERS_ENABLED=true
      # Hostname for n8n instance (used for URL generation)
      - N8N_HOST=localhost
      # Port for n8n to listen on inside the container
      - N8N_PORT=5678
      # Logging level: info, debug, warn, error
      - N8N_LOG_LEVEL=info
      # Set the timezone for workflows and logs
      - GENERIC_TIMEZONE=Europe/London  # Change as needed
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
volumes:
  n8n_data:
    external: true # Ensure to use the existing volume created externally